token_path="/home/siddhant_zeroandone/webapp/token.json"
password="upload_portal@2024"
OPENAI_API_KEY="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"
credentials_path="/home/siddhant_zeroandone/webapp/credentials_path.json"
